spring.application.name=spring-boot-journal-app

#mongodb connection
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://jainanshika095_db_user:I4815ay202Fl0AAg@cluster0.huivn0y.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=
#spring.data.mongodb.password=
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.security=DEBUG
logging.level.root=info

